//
//  StoryDetailPresenter.swift
//  TopStories
//
//  Created by Mozhgan on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class StoryDetailPresenter {

    // MARK: - Private properties -

    private unowned let view: StoryDetailViewInterface
    private let formatter: StoryDetailFormatterInterface
    private let interactor: StoryDetailInteractorInterface
    private let wireframe: StoryDetailWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: StoryDetailViewInterface,
        formatter: StoryDetailFormatterInterface,
        interactor: StoryDetailInteractorInterface,
        wireframe: StoryDetailWireframeInterface
    ) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension StoryDetailPresenter: StoryDetailPresenterInterface {
    var storyViewModel: StoryViewModel {
        self.formatter.format(story: self.interactor.stroy)
    }
}
