//
//  StoryDetailInterfaces.swift
//  TopStories
//
//  Created by Mozhgan on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol StoryDetailWireframeInterface: WireframeInterface {
}

protocol StoryDetailViewInterface: ViewInterface {
}

protocol StoryDetailPresenterInterface: PresenterInterface {
    var storyViewModel : StoryViewModel { get }
}

protocol StoryDetailFormatterInterface: FormatterInterface {
    func format(story: Story) -> StoryViewModel
}

protocol StoryDetailInteractorInterface: InteractorInterface {
    var stroy : Story { get }
}
