//
//  StoryDetailInterfaces.swift
//  TopStories
//
//  Created by Mozhgan on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol StoryDetailMoudleDelegate: WireframeInterface {
    func isBookmarked(url: String,value : Bool)
}
protocol StoryDetailWireframeInterface: WireframeInterface {
    func present(url: URL)
}

protocol StoryDetailViewInterface: ViewInterface {
    func didChangedBookmarked()
}

protocol StoryDetailPresenterInterface: PresenterInterface {
    var storyViewModel : StoryViewModel { get }
    func moreInfoPressed()
    func bookmark()
}

protocol StoryDetailFormatterInterface: FormatterInterface {
    func make(url : String) -> URL?
    func format(story: Story,isBookmarked : Bool) -> StoryViewModel
}

protocol StoryDetailInteractorInterface: InteractorInterface {
    var stroy : Story { get }
    var isBookMarked : Bool { get }
    func toggleBookmark()
    
}
