//
//  StoryDetailWireframe.swift
//  TopStories
//
//  Created by Mozhgan on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import SafariServices

final class StoryDetailWireframe: BaseWireframe<StoryDetailViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(story : Story,
         isBookmarked : Bool,
         moudleDelegate : StoryDetailMoudleDelegate) {
        let moduleViewController = StoryDetailViewController(nibName: nil, bundle: nil)
        super.init(viewController: moduleViewController)
        let formatter = StoryDetailFormatter()
        let interactor = StoryDetailInteractor(story: story, isBookMarked: isBookmarked)
        let presenter = StoryDetailPresenter(view: moduleViewController,
                                             formatter: formatter,
                                             interactor: interactor,
                                             wireframe: self,
                                             moudleDelegate: moudleDelegate)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension StoryDetailWireframe: StoryDetailWireframeInterface {
    func present(url: URL) {
        let  vc = SFSafariViewController(url: url)
        self.viewController.present(vc, animated: true)
    }
    
}
