//
//  StoryDetailInteractor.swift
//  TopStories
//
//  Created by Mozhgan on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class StoryDetailInteractor : StoryDetailInteractorInterface {
    var isBookMarked: Bool
    var stroy: Story
    init(story : Story,
         isBookMarked: Bool) {
        self.stroy = story
        self.isBookMarked = isBookMarked
    }
    func toggleBookmark() {
        isBookMarked = !isBookMarked
    }
}
