//
//  StoryDetailFormatter.swift
//  TopStories
//
//  Created by Mozhgan on 9/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class StoryDetailFormatter {
}

// MARK: - Extensions -

extension StoryDetailFormatter: StoryDetailFormatterInterface {
    func format(story: Story) -> StoryViewModel {
        StoryViewModel(story: story)
    }
    
}
struct StoryViewModel : CustomStringConvertible {
    var title : String {
        story.title ?? ""
    }
    var description: String {
        story.abstract ?? ""
    }
    var coverUrl : String? {
        guard let superJumbo = self.story.multimedia?.first(where: {$0.format == .superJumbo}) else {
            return nil
        }
        return  superJumbo.url
    }
    var date : String {
        guard let updatedDate = story.updatedDate else { return "" }
        let convertDateFormatter = DateFormatter()
        convertDateFormatter.dateFormat = "MMM dd yyyy h:mm a"
        return convertDateFormatter.string(from: updatedDate)
    }
    
    let story : Story
    
    init(story : Story) {
        self.story = story
    }
}
