//
//  WebInteractor.swift
//  TopStories
//
//  Created by Mozhgan on 9/7/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class WebInteractor : WebInteractorInterface {
    var urlRequest: URLRequest
    init(urlRequest: URLRequest) {
        self.urlRequest = urlRequest
    }
}
