//
//  WebInterfaces.swift
//  TopStories
//
//  Created by Mozhgan on 9/7/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol WebWireframeInterface: WireframeInterface {
}

protocol WebViewInterface: ViewInterface {
    func load(request : URLRequest)
}

protocol WebPresenterInterface: PresenterInterface {
    func loadView()
}

protocol WebInteractorInterface: InteractorInterface {
    var urlRequest : URLRequest { get }
}
