//
//  WebPresenter.swift
//  TopStories
//
//  Created by Mozhgan on 9/7/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class WebPresenter {

    // MARK: - Private properties -

    private unowned let view: WebViewInterface
    private let interactor: WebInteractorInterface
    private let wireframe: WebWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: WebViewInterface,
        interactor: WebInteractorInterface,
        wireframe: WebWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension WebPresenter: WebPresenterInterface {
    func loadView() {
        self.view.load(request: self.interactor.urlRequest)
    }
}
