//
//  WebWireframe.swift
//  TopStories
//
//  Created by Mozhgan on 9/7/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class WebWireframe: BaseWireframe<WebViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(urlRequest: URLRequest) {
        let moduleViewController = WebViewController()
        super.init(viewController: moduleViewController)
        let interactor = WebInteractor(urlRequest: urlRequest)
        let presenter = WebPresenter(view: moduleViewController,interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension WebWireframe: WebWireframeInterface {
}
