//
//  StoryListWireframe.swift
//  TopStories
//
//  Created by Mozhgan on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class StoryListWireframe: BaseWireframe<StoryListViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = StoryListViewController()
        super.init(viewController: moduleViewController)

        let formatter = StoryListFormatter()
        let interactor = StoryListInteractor()
        let presenter = StoryListPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension StoryListWireframe: StoryListWireframeInterface {
}
