//
//  StoryListInterfaces.swift
//  TopStories
//
//  Created by Mozhgan on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
enum StoryListDesination : Equatable {
    static func == (lhs: StoryListDesination, rhs: StoryListDesination) -> Bool {
        switch (lhs,rhs) {
        case (.detail(_,let lhsStory,_),.detail(let rhsDelegate,let rhsStory,_)) :
            return lhsStory == rhsStory
        }
    }
    
    case detail(delegate : StoryDetailMoudleDelegate, item : Story,isBookmarked : Bool)
}

protocol StoryListWireframeInterface: WireframeInterface {
    func present(message: String)
    func routeTo(desination : StoryListDesination)
}

protocol StoryListViewInterface: ViewInterface {
    func startLoading()
    func stopLoading()
    func show(viewState : StoryListViewController.ViewState)
}

protocol StoryListPresenterInterface: PresenterInterface {
    var numberOfsection : Int { get }
    var numberOfRows : Int { get }
    func viewDidAppear()
    func didSelect(idx: Int)
    func rowFor(idx: Int) -> StoryCellViewModel
    func pullToRefresh()
}

protocol StoryListFormatterInterface: FormatterInterface {
    func format(story: Story,isBookmarked : Bool) -> StoryCellViewModel
}

protocol StoryListInteractorInterface: InteractorInterface {
    
    init(worker : TopStoryNetworkManagerProtocol)
    
    func fetch(result: @escaping ((Result<Stories, APIError>) -> Void))
    func didChangedBookmarked(url : String,value : Bool)
    func isBookmarked(url : String) -> Bool
    func item(for index : Int) -> Story
}
