//
//  StoryListInterfaces.swift
//  TopStories
//
//  Created by Mozhgan on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol StoryListWireframeInterface: WireframeInterface {
}

protocol StoryListViewInterface: ViewInterface {
}

protocol StoryListPresenterInterface: PresenterInterface {
}

protocol StoryListFormatterInterface: FormatterInterface {
}

protocol StoryListInteractorInterface: InteractorInterface {
}
