//
//  StoryListFormatter.swift
//  TopStories
//
//  Created by Mozhgan on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

fileprivate extension Layout {
    static let emptyState : UIImage = UIImage(imageLiteralResourceName: "EmptyState")
}

final class StoryListFormatter {
}

// MARK: - Extensions -

extension StoryListFormatter: StoryListFormatterInterface {
}

extension StoryListViewController {
    enum ViewState {
        case loadingView
        case emptyView
        case storyView(item : Story)
        
        var view : UIView {
            switch self {
            case .loadingView:
                return ActivityIndicator(with: .init())
            case .emptyView:
                return UIImageView(image: Layout.emptyState)
            case .storyView(let item):
                return StoryView(configuration: .init(viewModel: .init(story: item)))
            }
        }
    }
}

struct StoryViewModel : CustomStringConvertible {
    var thumbnailImage : UIImage?
    var img : UIImage?
    
    var title : String {
        story.title ?? ""
    }
    var description: String {
        story.section ?? ""
    }
    private let story : Story
    
    init(story : Story) {
        self.story = story
    }
}
