//
//  StoryListFormatter.swift
//  TopStories
//
//  Created by Mozhgan on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class StoryListFormatter {
}

// MARK: - Extensions -

extension StoryListFormatter: StoryListFormatterInterface {
    func format(stories: Stories) -> StoryListViewController.ViewState {
        guard let results = stories.results,!results.isEmpty else {
            return .emptyState
        }
        return .list(results.map({StoryCellViewModel.init(story: $0)}))
    }
    
}

extension StoryListViewController {
    enum ViewState {
        case list([StoryCellViewModel])
        case emptyState
    }
}

struct StoryCellViewModel {
    var title : String {
        story.title ?? ""
    }
    var largeThumbnailUrl : String? {
        guard let largeThumbnail = self.story.multimedia?.first(where: {$0.format == .largeThumbnail}) else {
            return nil
        }
        return largeThumbnail.url
    }
    
    let story : Story
    
    init(story : Story) {
        self.story = story
    }
}
