//
//  StoryListPresenter.swift
//  TopStories
//
//  Created by Mozhgan on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class StoryListPresenter : StoryListPresenterInterface {
    // MARK: - Public properties -
    var numberOfsection: Int {
        1
    }
    // MARK: - Private properties -

    private unowned let view: StoryListViewInterface
    private let formatter: StoryListFormatterInterface
    private let interactor: StoryListInteractorInterface
    private let wireframe: StoryListWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: StoryListViewInterface,
        formatter: StoryListFormatterInterface,
        interactor: StoryListInteractorInterface,
        wireframe: StoryListWireframeInterface
    ) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    func viewDidAppear() {
        self.view.startLoading()
        self.interactor.fetch { [weak self] result in
            guard let self = self else { return }
            self.view.stopLoading()
            switch result {
            case .success(let value):
                self.view.show(viewState: self.formatter.format(stories: value))
            case .failure(let error):
                self.wireframe.present(message: error.localizedDescription)
            }
        }
    }
    
    func didSelect(viewModel: StoryViewModel) {
        self.wireframe.routeTo(desination: .detail(item: viewModel.story))
    }
}
